packages:
  - apps/*
  - packages/*
  - configs/*
catalog:
  eslint: 9.39.2
  prettier: 3.7.4
  zod: 4.3.3
  globals: 15.15.0
  typescript: 5.9.3
  dotenv: 17.2.3
  lodash-es: 4.17.22
  '@types/lodash-es': 4.17.12
  '@types/node': 24.0.0
  tsdown: 0.18.4
  tsx: 4.19.2
  '@swc/core': 1.15.17
  '@swc-node/register': 1.10.10
  unplugin-swc: 1.5.4
  vitest: 4.0.18
  '@vitest/ui': 4.0.18
  vite: 7.3.0
  hono: 4.11.3
  '@orpc/contract': 1.13.2
  '@orpc/server': 1.13.2
  '@orpc/client': 1.13.2
  '@orpc/tanstack-query': 1.13.2
  '@orpc/zod': 1.13.2
  '@orpc/openapi': 1.13.2
  better-auth: 1.4.18
  '@typescript/native-preview': 7.0.0-dev.20251231.1
onlyBuiltDependencies:
  - '@swc/core'
patchedDependencies:
  better-auth: patches/better-auth.patch
