packages:
  - 'apps/*'
  - 'packages/*'

# Use pnpm catalogs for shared dependencies
catalog:
  '@eslint/compat': 2.0.0
  '@eslint/js': 9.39.2
  '@stylistic/eslint-plugin': 5.6.1
  eslint: 9.39.2
  eslint-config-airbnb-extended: 2.3.3
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-n: 17.23.1
  eslint-plugin-prettier: 5.5.4
  prettier: 3.7.4
  typescript-eslint: 8.51.0
  '@typescript-eslint/eslint-plugin': 8.51.0
  '@typescript-eslint/parser': 8.51.0
  '@trivago/prettier-plugin-sort-imports': 6.0.0
  zod: 4.3.3
  globals: 15.15.0
  typescript: 5.9.3
  dotenv: 17.2.3
  lodash-es: 4.17.22
  '@types/lodash-es': 4.17.12
  tsdown: 0.18.4
  '@orpc/contract': 1.13.2
  '@orpc/server': 1.13.2
  '@orpc/client': 1.13.2
  '@orpc/tanstack-query': 1.13.2
  '@orpc/zod': 1.13.2
  '@orpc/openapi': 1.13.2
  better-auth: 1.4.18
  '@typescript/native-preview': 7.0.0-dev.20251231.1
patchedDependencies:
  better-auth: patches/better-auth.patch
